version: '3.8'

services:
  db:
    container_name: reserv-db1
    image: reserv-db
    environment:
      POSTGRES_PASSWORD: orkideaframework
    build:
      context: .
      dockerfile: db/Dockerfile
    volumes:
      - ./reserv-vol:/var/lib/postgresql/data

  adminer:
    container_name: adminer1
    image: adminer
    ports:
      - 8080:8080
  
  app:
    container_name: reserv-app1
    image: reserv-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_SERV: db
      DATABASE_PASS: orkideaframework
      GCALENDAR_ID: yourcalendar@gmail.com
      GOOGLE_APPLICATION_CREDENTIALS: ../../../keys.json
    ports:
      - 8081:80
    depends_on:
      - db
